name: Tyk Grpc Plugin
on:
  push:
    branches: [main]
permissions:
  contents: read 
jobs:
  test:
    strategy:
      matrix:
        os: [luminosita-ubuntu]
        go: ["1.23"]  
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    environment: dev
    runs-on: luminosita-ubuntu
    steps:
      - run: echo " The name of your br anch is ${{ GitHub.ref }} and your repository is ${{ GitHub.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo " The ${{ GitHub.repository }} repository has been cloned to the runner." 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          outputs: type=local,dest=${{ github.workspace }}
      - name: List files in the working directory
        run: |
          ls
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload Plugin to Nexus
        run: curl -v -k -u admin:${{ secrets.NEXUS_PASSWORD }} --upload-file ${{ github.workspace }}/bundle-latest.zip ${{ vars.NEXUS_TYK_REPO_URL }}/net/emisia/grpc/$VERSION/grpc-$VERSION-$SNAPSHOT.zip
        env:
          SNAPSHOT: SNAPSHOT-${{ steps.date.outputs.date }}
          VERSION: "0.0.1"
      - run: echo " This job's status is ${{ job.status }}."